development:
  adapter: postgresql
  encoding: unicode
  database: showstud
  pool: 5
  username: acanyon
  host: localhost
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: showstud_test
  pool: 5
  username: acanyon
  password: 


production:
  adapter: postgresql
  encoding: unicode
  database: showstud_production
  pool: 5
  username: 
  password:

